In [1]:
import pandas as pd
import numpy as np
from fredapi import Fred
fred = Fred(api_key='c2142066cce2050ddf167730db63188d')

In [7]:
#data['date'] = data['date'].apply(lambda x: str(x)[0:10])
#data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
#data.tail()

data = fred.get_series_all_releases('usslind')
data
#data['diff'] = data['realtime_start'] - data['date']
#data['date'] = data['date'].apply(lambda x: str(x)[0:10])
#data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
#data['diff'] = data['diff'].apply(lambda x: x.days)

                      date       realtime_start value
0      1982-01-01 00:00:00  2011-02-01 00:00:00 -1.85
1      1982-01-01 00:00:00  2011-03-22 00:00:00 -2.12
2      1982-01-01 00:00:00  2011-03-31 00:00:00 -2.09
3      1982-01-01 00:00:00  2011-04-28 00:00:00 -2.11
4      1982-01-01 00:00:00  2011-05-31 00:00:00 -2.09
5      1982-01-01 00:00:00  2011-06-28 00:00:00 -2.11
6      1982-01-01 00:00:00  2011-08-02 00:00:00 -2.06
7      1982-01-01 00:00:00  2011-08-30 00:00:00 -2.04
8      1982-01-01 00:00:00  2011-09-29 00:00:00 -2.03
9      1982-01-01 00:00:00  2011-11-01 00:00:00    -2
10     1982-01-01 00:00:00  2011-12-29 00:00:00 -2.01
11     1982-01-01 00:00:00  2012-02-02 00:00:00 -1.98
12     1982-01-01 00:00:00  2012-03-20 00:00:00 -1.91
13     1982-01-01 00:00:00  2012-04-03 00:00:00 -2.25
14     1982-01-01 00:00:00  2012-04-27 00:00:00 -0.62
15     1982-01-01 00:00:00  2012-06-28 00:00:00 -0.75
16     1982-01-01 00:00:00  2012-07-31 00:00:00 -0.74
17     1982-01-01 00:00:00  2012-08-28 00:00:00 -0.73
18     1982-01-01 00:00:00  2012-10-02 00:00:00 -0.75
19     1982-01-01 00:00:00  2013-01-03 00:00:00 -0.73
20     1982-01-01 00:00:00  2013-01-31 00:00:00 -0.76
21     1982-01-01 00:00:00  2013-03-26 00:00:00 -0.71
22     1982-01-01 00:00:00  2013-05-28 00:00:00    -1
23     1982-01-01 00:00:00  2013-07-02 00:00:00 -1.07
24     1982-01-01 00:00:00  2013-07-30 00:00:00 -0.78
25     1982-01-01 00:00:00  2013-10-01 00:00:00 -0.77
26     1982-01-01 00:00:00  2013-12-04 00:00:00  -0.8
27     1982-01-01 00:00:00  2014-02-04 00:00:00 -0.78
28     1982-01-01 00:00:00  2014-03-24 00:00:00 -0.79
29     1982-01-01 00:00:00  2014-04-03 00:00:00 -1.08
...                    ...                  ...   ...
21303  2017-05-01 00:00:00  2017-12-05 00:00:00  1.36
21304  2017-05-01 00:00:00  2017-12-29 00:00:00  1.38
21305  2017-05-01 00:00:00  2018-02-02 00:00:00  1.37
21306  2017-06-01 00:00:00  2017-08-01 00:00:00  1.42
21307  2017-06-01 00:00:00  2017-08-29 00:00:00   1.4
21308  2017-06-01 00:00:00  2017-10-05 00:00:00  1.39
21309  2017-06-01 00:00:00  2017-12-05 00:00:00  1.42
21310  2017-06-01 00:00:00  2017-12-29 00:00:00  1.41
21311  2017-06-01 00:00:00  2018-02-02 00:00:00  1.45
21312  2017-07-01 00:00:00  2017-08-29 00:00:00  1.22
21313  2017-07-01 00:00:00  2017-10-05 00:00:00  1.23
21314  2017-07-01 00:00:00  2017-11-02 00:00:00  1.17
21315  2017-07-01 00:00:00  2017-12-05 00:00:00  1.19
21316  2017-07-01 00:00:00  2017-12-29 00:00:00  1.17
21317  2017-07-01 00:00:00  2018-02-02 00:00:00  1.18
21318  2017-08-01 00:00:00  2017-10-05 00:00:00  1.29
21319  2017-08-01 00:00:00  2017-11-02 00:00:00  1.12
21320  2017-08-01 00:00:00  2017-12-05 00:00:00  1.27
21321  2017-08-01 00:00:00  2017-12-29 00:00:00  1.26
21322  2017-08-01 00:00:00  2018-02-02 00:00:00  1.23
21323  2017-09-01 00:00:00  2017-11-02 00:00:00  0.87
21324  2017-09-01 00:00:00  2017-12-05 00:00:00   1.2
21325  2017-09-01 00:00:00  2017-12-29 00:00:00  1.13
21326  2017-09-01 00:00:00  2018-02-02 00:00:00   1.1
21327  2017-10-01 00:00:00  2017-12-05 00:00:00  1.72
21328  2017-10-01 00:00:00  2017-12-29 00:00:00  1.62
21329  2017-10-01 00:00:00  2018-02-02 00:00:00  1.56
21330  2017-11-01 00:00:00  2017-12-29 00:00:00   1.4
21331  2017-11-01 00:00:00  2018-02-02 00:00:00  1.39
21332  2017-12-01 00:00:00  2018-02-02 00:00:00   1.4

[21333 rows x 3 columns]

In [20]:
table = pd.DataFrame({'date':pd.date_range('1970-01-01','2018-03-17')})
table['date'] = table['date'].apply(lambda x: str(x)[0:10])
#table = table.set_index('date')

#restricts each reporting period to the original report date, ignoring revisions
def add_first(dt, st, v, sym):
    global df
    if(len(df[df[sym+'_dt'].str.contains(dt)]) == 0): #&
        #abs((pd.to_datetime(dt) - pd.to_datetime(st)).days) < 300):
        tmp = pd.DataFrame({sym+'_dt':[dt], 'date':[st], sym:[v]})
        df = df.append(tmp, ignore_index=True)

#ignores historical data that is dumped all on the same day when the survey first becomes active
def add_indicator(sym):
    global table
    global df
    data = fred.get_series_all_releases(sym)
    data['diff'] = data['realtime_start'] - data['date']
    data['diff'] = data['diff'].apply(lambda x: x.days)
    data['date'] = data['date'].apply(lambda x: str(x)[0:10])
    data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
    
    if(sym not in ['VIXCLS','DGS10']):
        diff = 60
    else:
        diff = 2
    data = data[data['diff'] < diff]
    
    df = pd.DataFrame(columns=[sym+'_dt','date',sym])
    [add_first(row[1],row[2],row[3],sym) for row in data.itertuples()]
    #table = table.join(df.set_index('realtime_start'))
    table = table.merge(df,on='date',how='left')
    
def add_first_ind(dt, st, v,):
    global df
    if(len(df[df['obs_start_dt'].str.contains(dt)]) == 0): 
        tmp = pd.DataFrame({'obs_start_dt':[dt], 'release_dt':[st], 'value':[v]})
        df = df.append(tmp, ignore_index=True)
    
def individual_df(sym):
    global df
    data = fred.get_series_all_releases(sym)
    data['date'] = data['date'].apply(lambda x: str(x)[0:10])
    data['realtime_start'] = data['realtime_start'].apply(lambda x: str(x)[0:10])
    df = pd.DataFrame(columns=['obs_start_dt','release_dt','value'])
    [add_first_ind(row[1],row[2],row[3]) for row in data.itertuples()]
    df.to_csv(sym+'.csv')

In [21]:
symbols = ['HOUST','UNRATENSA','EMRATIO','UEMPMED','UMCSENT','USSLIND','KCFSI','IPMAN','VIXCLS','DGS10']

#[add_indicator(sym) for sym in symbols]

[individual_df(sym) for sym in symbols]

[None, None, None, None, None, None, None, None, None, None]

In [5]:
table.fillna(method='ffill',inplace=True)
table

,date,HOUST,HOUST_dt,UNRATENSA,UNRATENSA_dt,EMRATIO,EMRATIO_dt,UEMPMED,UEMPMED_dt,UMCSENT,...,USSLIND,USSLIND_dt,KCFSI,KCFSI_dt,IPMAN,IPMAN_dt,VIXCLS,VIXCLS_dt,DGS10,DGS10_dt
0,1970-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1970-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1970-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1970-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1970-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1970-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1970-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1970-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1970-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1970-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1970-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1970-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1970-01-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1970-01-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1970-01-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1970-01-16,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1970-01-17,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1970-01-18,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1970-01-19,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1970-01-20,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1970-01-21,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1970-01-22,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1970-01-23,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1970-01-24,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1970-01-25,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1970-01-26,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1970-01-27,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1970-01-28,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1970-01-29,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1970-01-30,1245.0,1969-12-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17619,2018-02-17,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17620,2018-02-18,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17621,2018-02-19,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.46,2018-02-16,2.90,2018-02-15
17622,2018-02-20,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.46,2018-02-19,2.90,2018-02-15
17623,2018-02-20,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,20.60,2018-02-20,2.90,2018-02-15
17624,2018-02-21,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,20.02,2018-02-21,2.88,2018-02-20
17625,2018-02-22,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,18.72,2018-02-22,2.94,2018-02-21
17626,2018-02-23,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17627,2018-02-24,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17628,2018-02-25,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,16.49,2018-02-23,2.92,2018-02-22
17629,2018-02-26,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,15.80,2018-02-26,2.92,2018-02-22
17630,2018-02-27,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,18.59,2018-02-27,2.86,2018-02-26
17631,2018-02-28,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.85,2018-02-28,2.90,2018-02-27
17632,2018-03-01,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,22.47,2018-03-01,2.87,2018-02-28
17633,2018-03-02,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17634,2018-03-03,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17635,2018-03-04,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,19.59,2018-03-02,2.87,2018-02-28
17636,2018-03-05,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,18.73,2018-03-05,2.87,2018-02-28
17637,2018-03-06,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,18.36,2018-03-06,2.88,2018-03-05
17638,2018-03-07,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.82,2018-01-01,105.8657,2018-01-01,17.76,2018-03-07,2.88,2018-03-06
17639,2018-03-08,1326.0,2018-01-01,4.5,2018-01-01,60.1,2018-01-01,9.4,2018-01-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,16.54,2018-03-08,2.89,2018-03-07
17640,2018-03-09,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,14.64,2018-03-09,2.86,2018-03-08
17641,2018-03-10,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,14.64,2018-03-09,2.86,2018-03-08
17642,2018-03-11,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,14.64,2018-03-09,2.86,2018-03-08
17643,2018-03-12,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,15.78,2018-03-12,2.86,2018-03-08
17644,2018-03-13,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,16.35,2018-03-13,2.87,2018-03-12
17645,2018-03-14,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,17.23,2018-03-14,2.84,2018-03-13
17646,2018-03-15,1326.0,2018-01-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,105.8657,2018-01-01,16.59,2018-03-15,2.81,2018-03-14
17647,2018-03-16,1236.0,2018-02-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,106.8775,2018-02-01,16.59,2018-03-15,2.82,2018-03-15
17648,2018-03-17,1236.0,2018-02-01,4.4,2018-02-01,60.4,2018-02-01,9.3,2018-02-01,99.7,...,1.4,2017-11-01,-0.44,2018-02-01,106.8775,2018-02-01,16.59,2018-03-15,2.82,2018-03-15

In [6]:
table.to_csv('indicators.csv')